version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_INIIT_ARGS: "--encoding=UTF-8"
    cap_add:
      - SYS_NICE
    user: root

  app:
    build: 
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - type: bind
        source: "./"
        target: "/people-logger"

